# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  
  config.vm.define "docker" do |node|
  
    node.vm.box               = "generic/ubuntu2004"
    node.vm.box_check_update  = false
    node.vm.box_version       = "3.3.0"
    node.vm.hostname          = "docker"

    node.vm.network "private_network", ip: "192.168.56.100"
  
    node.vm.provider :virtualbox do |v|
      v.name    = "docker"
      v.memory  = 4096
      v.cpus    =  2
    end
    
  end

end