version: '3'
services:
  
  mongodb:
    image: mongo:4.2
    volumes:
      - /data/mongo_data:/data/db
    ports:
      - 27017:27017
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    volumes:
      - /data/es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - ES_JAVA_OPTS=-Xms4096m -Xmx4096m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 8g
    ports:
      - 9200:9200
  
  skywalking-oap-server:
    image: apache/skywalking-oap-server:8.9.1
    environment:
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
      - SW_STORAGE_ES_INDEX_REPLICAS_NUMBER=0
    links:
      - elasticsearch
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - 11800:11800
      - 12800:12800

  skywalking-ui:
    image: apache/skywalking-ui:8.9.1
    environment:
      - SW_OAP_ADDRESS=http://skywalking-oap-server:12800
    links:
      - skywalking-oap-server
    restart: always
    depends_on:
      - skywalking-oap-server
    ports:
      - 8080:8080  

  graylog:
    image: graylog/graylog:4.2
    volumes:
      - /data/graylog_data:/usr/share/graylog/data
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_ROOT_TIMEZONE=Asia/Shanghai
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    links:
      - mongodb:mongo
      - elasticsearch
    restart: always
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
