version: '3.4'

networks: 
  kong-net:

volumes:
  kong-datastore:

services:
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    volumes:
      - kong-datastore:/var/lib/postgresql/data
    networks:
      - kong-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong

  kong:
    build:
      context: ""
    image: kong-oidc:latest
    container_name: kong
    depends_on:
      - kong-database
    volumes:
      - ./kong.yml:/home/kong/kong.yml
    networks:
      - kong-net
    ports:
      - "8000:8000" # Listener
      - "8443:8443" # Listener  (SSL)
      - "127.0.0.1:8001:8001" # Admin API
      - "127.0.0.1:8444:8444" # Admin API (SSL)
    environment:
      KONG_DATABASE:         postgres
      KONG_PG_HOST:          kong-database
      KONG_PG_PORT:          5432
      KONG_PG_DATABASE:      kong
      KONG_PG_USER:          kong
      KONG_PG_PASSWORD:      kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG:  /dev/stderr
      KONG_ADMIN_ERROR_LOG:  /dev/stderr
      KONG_PROXY_LISTEN:     0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN:     0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PLUGINS:          bundled,oidc

  konga:
    image: pantsel/konga:latest
    container_name: konga
    depends_on:
      - kong-database
      - kong
    networks:
      - kong-net
    ports:
      - "1337:1337"
    environment:
      DB_ADAPTER: postgres
      DB_URI: postgresql://kong:kong@kong-database:5432/kong
      NODE_ENV: production